export const metadata = {
    title: "Squealer",
    description: "Generated by Next.js",
};

import Header from "@/components/Header";
import Navbar from "@/components/Navbar/Navbar";
import LayoutWrapper from "@/components/LayoutWrapper";

import "styles/globals.css";

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <Header />
                <LayoutWrapper>{children}</LayoutWrapper>
                <Navbar />
            </body>
        </html>
    );
}
