export const metadata = {
    title: "Squealer",
    description: "Generated by Next.js",
};

import "styles/globals.css";

import NextAuthProvider from "@/components/Auth/NextAuthProvider";
import dynamic from "next/dynamic";

const ServiceRegister = dynamic(
    () => import("@/components/PushNotifications/ServiceRegister"),
    {
        ssr: false,
    }
);

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <link rel="manifest" href="/manifest.json" />
                <meta name="theme-color" content="#111b21" />
            </head>
            <body>
                <NextAuthProvider>
                    <ServiceRegister />
                    {children}
                </NextAuthProvider>
            </body>
        </html>
    );
}
