export const metadata = {
    title: "Squealer",
    description: "Generated by Next.js",
};

import Header from "@/components/Header";
import Navbar from "@/components/Navbar/Navbar";
import LayoutWrapper from "@/components/LayoutWrapper";
import Menu from "@/components/Navbar/Menu";

import "styles/globals.css";

export default function GeneralLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            <div className="flex flex-row">
                <div className="hidden md:block md:h-screen md:z-[1001] md:sticky md:top-0">
                    <Menu />
                </div>
                <main className="w-full">
                    <Header />
                    <LayoutWrapper>{children}</LayoutWrapper>
                </main>
            </div>
            <Navbar />
        </>
    );
}
